[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4CC9F0"
backgroundColor = "#07111F"
secondaryBackgroundColor = "#0F2238"
textColor = "#EAF3FF"
